"use client";

import React from "react";
import { motion } from "framer-motion";
import { Users, BookOpen, Star, Cpu } from "lucide-react";

export default function Stats() {
  const stats = [
    {
      icon: Users,
      value: "1.2M+",
      label: "Readings Generated",
      desc: "Cosmic reports generated by our alignment engine.",
      color: "text-nebula-purple",
      glow: "cosmic-glow-purple",
    },
    {
      icon: BookOpen,
      value: "12+",
      label: "Astrology Systems",
      desc: "Western, Vedic, Hellenistic, & Chinese calculations.",
      color: "text-celestial-blue",
      glow: "cosmic-glow-blue",
    },
    {
      icon: Star,
      value: "99.2%",
      label: "Accuracy Rating",
      desc: "Users reporting resonance with their personalized maps.",
      color: "text-aurora-pink",
      glow: "cosmic-glow-pink",
    },
    {
      icon: Cpu,
      value: "100%",
      label: "AI-Powered Interpretation",
      desc: "Intelligent correlation of natal maps and star positions.",
      color: "text-nebula-purple",
      glow: "cosmic-glow-purple",
    },
  ];

  return (
    <section className="py-20 relative overflow-hidden" id="features">
      {/* Stars Backdrop */}
      <div className="absolute inset-0 space-stars -z-10" />

      <div className="max-w-7xl mx-auto px-6">
        <motion.div
          className="text-center max-w-2xl mx-auto mb-16"
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
        >
          <h2 className="font-display text-3xl sm:text-4xl font-extrabold mb-4">
            Decoded by AI. Trusted by Seekers.
          </h2>
          <p className="text-sm sm:text-base opacity-75 text-muted">
            AstraNova computes exact planetary positions based on real-time orbital calculations, compiling ancient insights into modern, readable maps.
          </p>
        </motion.div>

        {/* Stats Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
          {stats.map((stat, i) => (
            <motion.div
              key={i}
              className={`glassmorphism rounded-2xl p-6 relative group overflow-hidden ${stat.glow} transition-all duration-300 hover:-translate-y-1`}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5, delay: i * 0.1 }}
            >
              {/* Glow accent */}
              <div className="absolute top-0 right-0 w-24 h-24 bg-gradient-to-bl from-nebula-purple/10 to-transparent rounded-bl-full group-hover:scale-110 transition-transform duration-500" />
              
              <div className="flex items-center space-x-4 mb-4">
                <div className={`p-3 rounded-xl bg-space-navy/5 dark:bg-space-navy/40 border border-[var(--card-border)] ${stat.color}`}>
                  <stat.icon className="w-6 h-6" />
                </div>
                <div>
                  <h3 className="text-3xl font-display font-extrabold tracking-tight">
                    {stat.value}
                  </h3>
                </div>
              </div>

              <h4 className="font-semibold text-sm tracking-wider uppercase mb-2">
                {stat.label}
              </h4>
              <p className="text-xs opacity-75 text-muted leading-relaxed">
                {stat.desc}
              </p>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}
